version: '3.8'
services:
  app:
    container_name: mustafa-above-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1235:3000"
    pull_policy: build
