name: Docker Stable Image CI
# checking action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/mustafa-ass-scd:stable
          docker push ghcr.io/${{ github.repository_owner }}/mustafa-ass-scd:stable
  update:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/beta'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send POST request to Portainer webhook
        run: |
          curl -k -X POST -H "Content-Type: application/json" \
               -d '{"key": "value"}' \
               https://162.19.224.10:9443/api/stacks/webhooks/3323bb90-c0ae-4a47-a9cf-41b5de8a525c
